export const SET_COURSE_DATA = 'SET_COURSE_DATA';
export const SET_COURSE_CONTENT_DATA ='SET_COURSE_CONTENT_DATA';
export const RESET_COURSE_CONTENT_DATA ='RESET_COURSE_CONTENT_DATA';
export const SET_QUIZ_DATA = 'SET_QUIZ_DATA';
export const SET_USER_DATA = 'SET_USER_DATA';
export const RESET_USER_DATA = 'RESET_USER_DATA';




